# Generated by Django 3.2.5 on 2022-07-09 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, default='img/avatars/default-user-img.png', null=True, upload_to='img/avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'contact'],
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, default='img/avatars/default-user-img.png', null=True, upload_to='img/avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'contact'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyer_du_client', models.BigIntegerField(null=True)),
                ('cotion_du_client', models.BigIntegerField(null=True)),
                ('type_du_client', models.CharField(default=None, max_length=50, null=True)),
                ('nombre_piece_desire', models.IntegerField(default=None, null=True)),
                ('zone_desire', models.CharField(default=None, max_length=50, null=True)),
                ('ville_desire', models.CharField(default=None, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='my_auths.client')),
            ],
            options={
                'ordering': ['client', 'loyer_du_client', 'cotion_du_client'],
            },
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('loyer', models.BigIntegerField(null=True)),
                ('cotion', models.BigIntegerField(null=True)),
                ('type_maison', models.CharField(max_length=200)),
                ('nombre_piece', models.IntegerField(null=True)),
                ('en_location', models.BooleanField(blank=True, default=False, null=True)),
                ('en_vente', models.BooleanField(blank=True, default=False, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='img/maisons/')),
                ('quan_dispo', models.IntegerField(blank=True, default=1, null=True)),
                ('ajoute_le', models.DateField(auto_now_add=True)),
                ('edite_le', models.DateField(auto_now=True)),
                ('occupee', models.BooleanField(default=False)),
                ('occupant', models.CharField(blank=True, max_length=200, null=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maisons', to='my_auths.landlord')),
            ],
        ),
    ]
